BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[T_CAMISA] (
    [CI_ID_CAMISA] INT NOT NULL IDENTITY(1,1),
    [CI_PECHO] INT NOT NULL,
    [CI_CINTURA] INT NOT NULL,
    [CI_CADERA] INT NOT NULL,
    [CI_ESPALDA] INT NOT NULL,
    [CI_HOMBRO] INT NOT NULL,
    [CI_CUELLO] INT NOT NULL,
    [CI_L_MANGA] INT NOT NULL,
    [CI_L_TOTAL] INT NOT NULL,
    [CI_BRAZO] INT NOT NULL,
    [CI_PUNO] INT NOT NULL,
    [CV_DETALLES] NVARCHAR(max) NOT NULL,
    CONSTRAINT [PK__T_CAMISA__658723BBAB061FC1] PRIMARY KEY CLUSTERED ([CI_ID_CAMISA])
);

-- CreateTable
CREATE TABLE [dbo].[T_CATALOGO] (
    [CI_ID_CATALOGO] INT NOT NULL IDENTITY(1,1),
    [CV_DESCRIPCION] NVARCHAR(70) NOT NULL,
    [CB_ESTADO] BIT NOT NULL,
    CONSTRAINT [PK__T_CATALO__924F56F8160F61AF] PRIMARY KEY CLUSTERED ([CI_ID_CATALOGO])
);

-- CreateTable
CREATE TABLE [dbo].[T_CATEGORIA] (
    [CI_ID_CATEGORIA] INT NOT NULL IDENTITY(1,1),
    [CV_DESCRIPCION] NVARCHAR(70) NOT NULL,
    [CB_ESTADO] BIT NOT NULL,
    CONSTRAINT [PK__T_CATEGO__0F0D10D42FE88E53] PRIMARY KEY CLUSTERED ([CI_ID_CATEGORIA])
);

-- CreateTable
CREATE TABLE [dbo].[T_CHALECO] (
    [CI_ID_CHALECO] INT NOT NULL IDENTITY(1,1),
    [CI_PECHO] INT NOT NULL,
    [CI_CINTURA] INT NOT NULL,
    [CI_CADERA] INT NOT NULL,
    [CI_L_TOTAL] INT NOT NULL,
    [CV_DETALLES] NVARCHAR(max) NOT NULL,
    CONSTRAINT [PK__T_CHALEC__93D395277E2A216B] PRIMARY KEY CLUSTERED ([CI_ID_CHALECO])
);

-- CreateTable
CREATE TABLE [dbo].[T_COMPRA] (
    [CI_ID_COMPRA] INT NOT NULL IDENTITY(1,1),
    [CI_ID_USUARIO] INT NOT NULL,
    [CF_FECHA_PAGO] DATETIME NOT NULL CONSTRAINT [DF__T_COMPRA__CF_FEC__628FA481] DEFAULT CURRENT_TIMESTAMP,
    [CD_SUBTOTAL] DECIMAL(10,2) NOT NULL,
    [CD_IMPUESTOS] DECIMAL(10,2) NOT NULL,
    [CD_DESCUENTOS] DECIMAL(10,2) NOT NULL,
    [CD_TOTAL] DECIMAL(10,2) NOT NULL,
    CONSTRAINT [PK__T_COMPRA__7F520FBBA5F0422B] PRIMARY KEY CLUSTERED ([CI_ID_COMPRA])
);

-- CreateTable
CREATE TABLE [dbo].[T_DETALLE_COMPRA] (
    [CI_ID_DETALLE_COMPRA] INT NOT NULL IDENTITY(1,1),
    [CI_ID_COMPRA] INT NOT NULL,
    [CI_ID_PRODUCTO] INT NOT NULL,
    [CI_CANTIDAD] INT NOT NULL,
    [CF_FECHA_ENTREGA] DATE NOT NULL,
    [CD_PRECIO] DECIMAL(10,2) NOT NULL,
    CONSTRAINT [PK__T_DETALL__0117900D2185568E] PRIMARY KEY CLUSTERED ([CI_ID_DETALLE_COMPRA])
);

-- CreateTable
CREATE TABLE [dbo].[T_ESTILO] (
    [CI_ID_ESTILO] INT NOT NULL IDENTITY(1,1),
    [CV_DESCRIPCION] NVARCHAR(50) NOT NULL,
    [CB_ESTADO] BIT NOT NULL,
    CONSTRAINT [PK__T_ESTILO__265385AB09B42A31] PRIMARY KEY CLUSTERED ([CI_ID_ESTILO])
);

-- CreateTable
CREATE TABLE [dbo].[T_ESTILO_X_PRODUCTO] (
    [CI_ID_ESTILO_X_PRODUCTO] INT NOT NULL IDENTITY(1,1),
    [CI_ID_ESTILO] INT NOT NULL,
    [CI_ID_PRODUCTO] INT NOT NULL,
    CONSTRAINT [PK__T_ESTILO__16FFE6CC29B6E58D] PRIMARY KEY CLUSTERED ([CI_ID_ESTILO_X_PRODUCTO])
);

-- CreateTable
CREATE TABLE [dbo].[T_PANTALON] (
    [CI_ID_PANTALON] INT NOT NULL IDENTITY(1,1),
    [CI_CINTURA] INT NOT NULL,
    [CI_CADERA] INT NOT NULL,
    [CI_TIRO] INT NOT NULL,
    [CI_RODILLA] INT NOT NULL,
    [CI_RUEDO] INT NOT NULL,
    [CI_LARGO] INT NOT NULL,
    [CV_DETALLES] NVARCHAR(max) NOT NULL,
    CONSTRAINT [PK__T_PANTAL__ED1FFB2BB4436643] PRIMARY KEY CLUSTERED ([CI_ID_PANTALON])
);

-- CreateTable
CREATE TABLE [dbo].[T_PRODUCTO] (
    [CI_ID_PRODUCTO] INT NOT NULL IDENTITY(1,1),
    [CV_NOMBRE] NVARCHAR(100) NOT NULL,
    [CV_FOTO] NVARCHAR(max) NOT NULL,
    [CI_ID_TELA] INT NOT NULL,
    [CD_PRECIO] DECIMAL(10,2) NOT NULL,
    [CI_ID_CATEGORIA] INT NOT NULL,
    [CI_ID_CATALOGO] INT NOT NULL,
    [CB_ESTADO] BIT NOT NULL,
    [CI_CANTIDAD] INT NOT NULL,
    CONSTRAINT [PK__T_PRODUC__ED80DC287D24C81B] PRIMARY KEY CLUSTERED ([CI_ID_PRODUCTO])
);

-- CreateTable
CREATE TABLE [dbo].[T_PRODUCTO_X_TALLA] (
    [CI_ID_PROD_X_TALLA] INT NOT NULL IDENTITY(1,1),
    [CI_ID_TALLA] INT NOT NULL,
    [CI_ID_PRODUCTO] INT NOT NULL,
    [CI_CANTIDAD] INT NOT NULL,
    CONSTRAINT [PK__T_PRODUC__EF0BA993FCA4E5A0] PRIMARY KEY CLUSTERED ([CI_ID_PROD_X_TALLA])
);

-- CreateTable
CREATE TABLE [dbo].[T_ROL] (
    [CI_ID_ROL] INT NOT NULL IDENTITY(1,1),
    [CV_DESCRIPCION] NVARCHAR(50),
    [CB_ESTADO] BIT,
    CONSTRAINT [PK__T_ROL__F64265C88CE2F772] PRIMARY KEY CLUSTERED ([CI_ID_ROL])
);

-- CreateTable
CREATE TABLE [dbo].[T_SACO] (
    [CI_ID_SACO] INT NOT NULL IDENTITY(1,1),
    [CI_PECHO] INT NOT NULL,
    [CI_CINTURA] INT NOT NULL,
    [CI_CADERA] INT NOT NULL,
    [CI_ESPALDA] INT NOT NULL,
    [CI_HOMBRO] INT NOT NULL,
    [CI_L_MANGA] INT NOT NULL,
    [CI_L_TOTAL] INT NOT NULL,
    [CI_BRAZO] INT NOT NULL,
    [CI_PUNO] INT NOT NULL,
    [CV_DETALLES] NVARCHAR(max) NOT NULL,
    CONSTRAINT [PK__T_SACO__10D66792AF35D361] PRIMARY KEY CLUSTERED ([CI_ID_SACO])
);

-- CreateTable
CREATE TABLE [dbo].[T_TALLA] (
    [CI_ID_TALLA] INT NOT NULL IDENTITY(1,1),
    [CV_TALLA] NVARCHAR(10) NOT NULL,
    CONSTRAINT [PK__T_TALLA__8B3370FA5ABE6F19] PRIMARY KEY CLUSTERED ([CI_ID_TALLA])
);

-- CreateTable
CREATE TABLE [dbo].[T_TELA] (
    [CI_ID_TELA] INT NOT NULL IDENTITY(1,1),
    [CV_NOMBRE] NVARCHAR(100) NOT NULL,
    [CV_FOTO] NVARCHAR(max) NOT NULL,
    [CD_PRECIO] DECIMAL(10,2) NOT NULL,
    [CB_ESTADO] BIT NOT NULL,
    CONSTRAINT [PK__T_TELA__D502DECDC977BFFB] PRIMARY KEY CLUSTERED ([CI_ID_TELA])
);

-- CreateTable
CREATE TABLE [dbo].[T_USUARIO] (
    [CI_ID_USUARIO] INT NOT NULL IDENTITY(1,1),
    [CV_NOMBRE] NVARCHAR(100) NOT NULL,
    [CV_APELLIDO1] NVARCHAR(100) NOT NULL,
    [CV_APELLIDO2] NVARCHAR(100) NOT NULL,
    [CV_CEDULA] NVARCHAR(50) NOT NULL,
    [CV_CORREO] NVARCHAR(100) NOT NULL,
    [CV_DIRECCION] NVARCHAR(max) NOT NULL,
    [CV_TELEFONO] NVARCHAR(20) NOT NULL,
    [CV_CLAVE] NVARCHAR(max) NOT NULL,
    [CI_ID_ROL] INT NOT NULL,
    [CB_ESTADO] BIT NOT NULL,
    CONSTRAINT [PK__T_USUARI__08FD7E8CC9BC2C5E] PRIMARY KEY CLUSTERED ([CI_ID_USUARIO]),
    CONSTRAINT [UQ__T_USUARI__C0EF9FF97E2DBEE3] UNIQUE NONCLUSTERED ([CV_CEDULA]),
    CONSTRAINT [UQ__T_USUARI__F61C67A31FD8BB9C] UNIQUE NONCLUSTERED ([CV_CORREO]),
    CONSTRAINT [UQ__T_USUARI__41BD9EBC8FD1CF62] UNIQUE NONCLUSTERED ([CV_TELEFONO])
);

-- CreateTable
CREATE TABLE [dbo].[T_USUARIO_X_MEDIDA] (
    [CI_ID_USUARIO_X_MEDIDA] INT NOT NULL IDENTITY(1,1),
    [CI_ID_USUARIO] INT NOT NULL,
    [CV_MEDIDAS_DE] NVARCHAR(100),
    [CI_ID_SACO] INT,
    [CI_ID_PANTALON] INT,
    [CI_ID_CAMISA] INT,
    [CI_ID_CHALECO] INT,
    [CB_ESTADO] BIT NOT NULL,
    CONSTRAINT [PK__T_USUARI__B7E05523CE5B3F07] PRIMARY KEY CLUSTERED ([CI_ID_USUARIO_X_MEDIDA])
);

-- AddForeignKey
ALTER TABLE [dbo].[T_COMPRA] ADD CONSTRAINT [FK_COMPRA_USUARIO] FOREIGN KEY ([CI_ID_USUARIO]) REFERENCES [dbo].[T_USUARIO]([CI_ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_DETALLE_COMPRA] ADD CONSTRAINT [FK_DETALLE_COMPRA_COMPRA] FOREIGN KEY ([CI_ID_COMPRA]) REFERENCES [dbo].[T_COMPRA]([CI_ID_COMPRA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_DETALLE_COMPRA] ADD CONSTRAINT [FK_DETALLE_COMPRA_PRODUCTO] FOREIGN KEY ([CI_ID_PRODUCTO]) REFERENCES [dbo].[T_PRODUCTO]([CI_ID_PRODUCTO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_ESTILO_X_PRODUCTO] ADD CONSTRAINT [FK_ESTILO_X_PRODUCTO_ESTILO] FOREIGN KEY ([CI_ID_ESTILO]) REFERENCES [dbo].[T_ESTILO]([CI_ID_ESTILO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_ESTILO_X_PRODUCTO] ADD CONSTRAINT [FK_ESTILO_X_PRODUCTO_PRODUCTO] FOREIGN KEY ([CI_ID_PRODUCTO]) REFERENCES [dbo].[T_PRODUCTO]([CI_ID_PRODUCTO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_PRODUCTO] ADD CONSTRAINT [FK_PRODUCTO_CATALOGO] FOREIGN KEY ([CI_ID_CATALOGO]) REFERENCES [dbo].[T_CATALOGO]([CI_ID_CATALOGO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_PRODUCTO] ADD CONSTRAINT [FK_PRODUCTO_CATEGORIA] FOREIGN KEY ([CI_ID_CATEGORIA]) REFERENCES [dbo].[T_CATEGORIA]([CI_ID_CATEGORIA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_PRODUCTO] ADD CONSTRAINT [FK_PRODUCTO_TELA] FOREIGN KEY ([CI_ID_TELA]) REFERENCES [dbo].[T_TELA]([CI_ID_TELA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_PRODUCTO_X_TALLA] ADD CONSTRAINT [FK_PROD_X_TALLA_PRODUCTO] FOREIGN KEY ([CI_ID_PRODUCTO]) REFERENCES [dbo].[T_PRODUCTO]([CI_ID_PRODUCTO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_PRODUCTO_X_TALLA] ADD CONSTRAINT [FK_PROD_X_TALLA_TALLA] FOREIGN KEY ([CI_ID_TALLA]) REFERENCES [dbo].[T_TALLA]([CI_ID_TALLA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_USUARIO] ADD CONSTRAINT [FK_USUARIO_ROL] FOREIGN KEY ([CI_ID_ROL]) REFERENCES [dbo].[T_ROL]([CI_ID_ROL]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_USUARIO_X_MEDIDA] ADD CONSTRAINT [FK_USUARIO_X_MEDIDA_CAMISA] FOREIGN KEY ([CI_ID_CAMISA]) REFERENCES [dbo].[T_CAMISA]([CI_ID_CAMISA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_USUARIO_X_MEDIDA] ADD CONSTRAINT [FK_USUARIO_X_MEDIDA_CHALECO] FOREIGN KEY ([CI_ID_CHALECO]) REFERENCES [dbo].[T_CHALECO]([CI_ID_CHALECO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_USUARIO_X_MEDIDA] ADD CONSTRAINT [FK_USUARIO_X_MEDIDA_PANTALON] FOREIGN KEY ([CI_ID_PANTALON]) REFERENCES [dbo].[T_PANTALON]([CI_ID_PANTALON]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_USUARIO_X_MEDIDA] ADD CONSTRAINT [FK_USUARIO_X_MEDIDA_SACO] FOREIGN KEY ([CI_ID_SACO]) REFERENCES [dbo].[T_SACO]([CI_ID_SACO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[T_USUARIO_X_MEDIDA] ADD CONSTRAINT [FK_USUARIO_X_MEDIDA_USUARIO] FOREIGN KEY ([CI_ID_USUARIO]) REFERENCES [dbo].[T_USUARIO]([CI_ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
